### ISSUE TITLE
npm err when doing a dbus build

### ISSUE THREAD

**Issue by alberttwong** [resin-io/resin-wifi-connect#103]
What I'm doing is upgrading the wifi connect code to support resin 2.0.   Following https://docs.resin.io/runtime/migrate-to-2.0/. Copied this project code into my project and merged the dockerfile (like before using resin 1.x).   Thought it would be an drop in upgrade but it wasn't. Reporting another error when npm is doing dbus build.

```
[Build]    Step 13 : RUN JOBS=MAX npm install --unsafe-perm --production     && npm cache clean
[Build]     ---> Running in be7cf738c160
[Build]    npm WARN deprecated bower@1.8.0: ..psst! While Bower is maintained, we recommend Yarn and Webpack for *new* front-end projects! Yarn's advantage is security and reliability, and Webpack's is support for both CommonJS and AMD projects. Currently there's no migration path but we hope you'll help us figure out one.
[Info]     Still working...
[Build]
[Build]    > dbus@0.2.19 install /app/pinballiot/node_modules/dbus
[Build]    > node-gyp configure build
[Build]    make: Entering directory '/app/pinballiot/node_modules/dbus/build'
[Build]      CXX(target) Release/obj.target/dbus/src/dbus.o
[Build]      CXX(target) Release/obj.target/dbus/src/connection.o
[Build]      CXX(target) Release/obj.target/dbus/src/signal.o
[Build]      CXX(target) Release/obj.target/dbus/src/encoder.o
[Build]      CXX(target) Release/obj.target/dbus/src/decoder.o
[Build]      CXX(target) Release/obj.target/dbus/src/introspect.o
[Build]      CXX(target) Release/obj.target/dbus/src/object_handler.o
[Build]      SOLINK_MODULE(target) Release/obj.target/dbus.node
[Build]      COPY Release/dbus.node
[Build]    make: Leaving directory '/app/pinballiot/node_modules/dbus/build'
[Build]    npm notice created a lockfile as package-lock.json. You should commit this file.
[Build]    added 52 packages in 72.581s
[Build]    npm ERR! As of npm@5, the npm cache self-heals from corruption issues and data extracted from the cache is guaranteed to be valid. If you want to make sure everything is consistent, use 'npm cache verify' instead.
[Build]    npm ERR!
[Build]    npm ERR! If you're sure you want to delete the entire cache, rerun this command with --force.
[Build]
[Build]    npm ERR! A complete log of this run can be found in:
[Build]    npm ERR!     /root/.npm/_logs/2017-06-14T04_16_41_794Z-debug.log
[Build]    Removing intermediate container be7cf738c160
[Error]    Build failed: The command '/bin/sh -c JOBS=MAX npm install --unsafe-perm --production     && npm cache clean' returned a non-zero code: 1
```

**Comment by alberttwong** [comment]
```
Alberts-MacBook-Pro:pinballiot alwong$ OBS=MAX npm install --unsafe-perm --production     && npm cache clean --force
npm WARN deprecated bower@1.8.0: ..psst! While Bower is maintained, we recommend Yarn and Webpack for *new* front-end projects! Yarn's advantage is security and reliability, and Webpack's is support for both CommonJS and AMD projects. Currently there's no migration path but we hope you'll help us figure out one.

> dbus@0.2.19 install /Users/alwong/sandbox/pinballiot/node_modules/dbus
> node-gyp configure build

  CXX(target) Release/obj.target/dbus/src/dbus.o
../src/dbus.cc:6:10: fatal error: 'dbus/dbus.h' file not found
#include <dbus/dbus.h>
         ^
1 error generated.
make: *** [Release/obj.target/dbus/src/dbus.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /Users/alwong/sandbox/pinballiot/node_modules/dbus
gyp ERR! node -v v6.10.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
resin-wifi-connect@2.0.7 /Users/alwong/sandbox/pinballiot
├── bluebird@3.5.0
├─┬ body-parser@1.17.2
│ ├── bytes@2.4.0
│ ├── content-type@1.0.2
│ ├─┬ debug@2.6.7
│ │ └── ms@2.0.0
│ ├── depd@1.1.0
│ ├── http-errors@1.6.1
│ ├── iconv-lite@0.4.15
│ ├─┬ on-finished@2.3.0
│ │ └── ee-first@1.1.1
│ ├─┬ raw-body@2.2.0
│ │ └── unpipe@1.0.0
│ └─┬ type-is@1.6.15
│   ├── media-typer@0.3.0
│   └─┬ mime-types@2.1.15
│     └── mime-db@1.27.0
├── bower@1.8.0
├── coffee-script@1.9.3
├─┬ express@4.15.3
│ ├── accepts@1.3.3
│ ├── array-flatten@1.1.1
│ ├── content-disposition@0.5.2
│ ├── cookie@0.3.1
│ ├── cookie-signature@1.0.6
│ ├─┬ debug@2.6.7
│ │ └── ms@2.0.0
│ ├── encodeurl@1.0.1
│ ├── escape-html@1.0.3
│ ├── etag@1.8.0
│ ├─┬ finalhandler@1.0.3
│ │ └─┬ debug@2.6.7
│ │   └── ms@2.0.0
│ ├── fresh@0.5.0
│ ├── merge-descriptors@1.0.1
│ ├── methods@1.1.2
│ ├── parseurl@1.3.1
│ ├── path-to-regexp@0.1.7
│ ├─┬ proxy-addr@1.1.4
│ │ ├── forwarded@0.1.0
│ │ └── ipaddr.js@1.3.0
│ ├── range-parser@1.2.0
│ ├─┬ send@0.15.3
│ │ ├── debug@2.6.7
│ │ ├── destroy@1.0.4
│ │ └── ms@2.0.0
│ ├── serve-static@1.12.3
│ ├── setprototypeof@1.0.3
│ ├── statuses@1.3.1
│ ├── utils-merge@1.0.0
│ └── vary@1.1.1
└── lodash@4.17.4

npm ERR! Darwin 16.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--unsafe-perm" "--production"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! dbus@0.2.19 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the dbus@0.2.19 install script 'node-gyp configure build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the dbus package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs dbus
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls dbus
npm ERR! There is likely additional logging output above.
```

**Comment by alberttwong** [comment]
upgrading to latest stable
```
sudo npm cache clean -f 
sudo npm install -g n 
sudo n stable 
```

```
../src/dbus.cc:6:10: fatal error: 'dbus/dbus.h' file not found
#include <dbus/dbus.h>
         ^
1 error generated.
1 error generated.
make: *** [Release/obj.target/dbus/src/object_handler.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [Release/obj.target/dbus/src/introspect.o] Error 1
1 error generated.
1 error generated.
1 error generated.
make: *** [Release/obj.target/dbus/src/connection.o] Error 1
make: *** [Release/obj.target/dbus/src/decoder.o] Error 1
make: *** [Release/obj.target/dbus/src/signal.o] Error 1
1 error generated.
make: *** [Release/obj.target/dbus/src/dbus.o] Error 1
1 error generated.
make: *** [Release/obj.target/dbus/src/encoder.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:285:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
gyp ERR! System Darwin 16.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /Users/alwong/sandbox/pinballiot/node_modules/dbus
gyp ERR! node -v v8.0.0
gyp ERR! node-gyp -v v3.6.1
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dbus@0.2.19 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the dbus@0.2.19 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by alberttwong** [comment]
```
Alberts-MacBook-Pro:pinballiot alwong$ cat /Users/alwong/.npm/_logs/2017-06-14T15_54_40_977Z-debug.log
```
```
790 silly finalize /Users/alwong/sandbox/pinballiot/node_modules/dbus
791 silly doParallel refresh-package-json 71
792 silly refresh-package-json /Users/alwong/sandbox/pinballiot/node_modules/dbus
793 silly doParallel preinstall 71
794 silly preinstall dbus@0.2.19
795 info lifecycle dbus@0.2.19~preinstall: dbus@0.2.19
796 silly lifecycle dbus@0.2.19~preinstall: no script for preinstall, continuing
797 silly doSerial build 71
798 silly build dbus@0.2.19
799 info linkStuff dbus@0.2.19
800 silly linkStuff dbus@0.2.19 has /Users/alwong/sandbox/pinballiot/node_modules as its parent node_modules
801 verbose linkBins dbus@0.2.19
802 verbose linkMans dbus@0.2.19
803 silly doSerial global-link 71
804 silly doParallel update-linked 71
805 silly doSerial install 71
806 silly install dbus@0.2.19
807 info lifecycle dbus@0.2.19~install: dbus@0.2.19
808 verbose lifecycle dbus@0.2.19~install: unsafe-perm in lifecycle true
809 verbose lifecycle dbus@0.2.19~install: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/alwong/sandbox/pinballiot/node_modules/dbus/node_modules/.bin:/Users/alwong/sandbox/pinballiot/node_modules/.bin:/Users/alwong/Downloads/google-cloud-sdk/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/git/bin:/usr/local/go/bin:/usr/local/MacGPG2/bin:/usr/local/apache-maven-3.2.3/bin:/Users/alwong/fabric8
810 verbose lifecycle dbus@0.2.19~install: CWD: /Users/alwong/sandbox/pinballiot/node_modules/dbus
811 silly lifecycle dbus@0.2.19~install: Args: [ '-c', 'node-gyp configure build' ]
812 silly lifecycle dbus@0.2.19~install: Returned: code: 1  signal: null
813 info lifecycle dbus@0.2.19~install: Failed to exec install script
814 verbose unlock done using /Users/alwong/.npm/_locks/staging-296d482e760609b9.lock for /Users/alwong/sandbox/pinballiot/node_modules/.staging
815 verbose stack Error: dbus@0.2.19 install: `node-gyp configure build`
815 verbose stack Exit status 1
815 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:283:16)
815 verbose stack     at emitTwo (events.js:125:13)
815 verbose stack     at EventEmitter.emit (events.js:213:7)
815 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
815 verbose stack     at emitTwo (events.js:125:13)
815 verbose stack     at ChildProcess.emit (events.js:213:7)
815 verbose stack     at maybeClose (internal/child_process.js:887:16)
815 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
816 verbose pkgid dbus@0.2.19
817 verbose cwd /Users/alwong/sandbox/pinballiot
818 verbose Darwin 16.6.0
819 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--unsafe-perm" "--production"
820 verbose node v8.0.0
821 verbose npm  v5.0.0
822 error code ELIFECYCLE
823 error errno 1
824 error dbus@0.2.19 install: `node-gyp configure build`
824 error Exit status 1
825 error Failed at the dbus@0.2.19 install script.
825 error This is probably not a problem with npm. There is likely additional logging output above.
826 verbose exit [ 1, true ]
```

**Comment by alberttwong** [comment]
Rolled back to a clean project without wifi code. Tested clean.  Manually added the new wifi code.   Works just fine.

**Comment by pcriadoperez** [comment]
I'm getting the same error.  Tried to create a new application and still can't build. What do you mean by project without wifi code?

**Comment by pcriadoperez** [comment]
Fixed it by adding to Dockerfile template:
 RUN apt-get update \
	&& apt-get install -y python \
		python-dev \
		python-dbus \
		python-pip \
        build-essential
