### ISSUE TITLE
TypeError: Cannot read property '0' of undefined (bluebird/js/main/async.js:43)

### ISSUE THREAD

**Issue by samouds** [resin-io/resin-wifi-connect#31]
Hello,

I'm having some trouble starting the portal mode, I have a Ralink RT5370 (http://www.amazon.fr/gp/product/B00BXWU7X4), but the portal mode never start due to this error :

```
04.03.16 10:39:43 [+0100] /usr/src/app/node_modules/bluebird/js/main/async.js:43
04.03.16 10:39:43 [+0100] fn = function () { throw arg; };
04.03.16 10:39:43 [+0100] ^
04.03.16 10:39:43 [+0100] TypeError: Cannot read property '0' of undefined
04.03.16 10:39:43 [+0100] at /usr/src/app/src/app.js:63:45
04.03.16 10:39:43 [+0100] at tryCatcher (/usr/src/app/node_modules/bluebird/js/main/util.js:26:23)
04.03.16 10:39:43 [+0100] at Function.Promise.attempt.Promise.try (/usr/src/app/node_modules/bluebird/js/main/method.js:31:24)
04.03.16 10:39:43 [+0100] at async.retry.callback.table (/usr/src/app/src/app.js:60:28)
04.03.16 10:39:43 [+0100] at /usr/src/app/node_modules/async/lib/async.js:651:21
04.03.16 10:39:43 [+0100] at /usr/src/app/node_modules/async/lib/async.js:718:13
04.03.16 10:39:43 [+0100] at iterate (/usr/src/app/node_modules/async/lib/async.js:262:13)
04.03.16 10:39:43 [+0100] at /usr/src/app/node_modules/async/lib/async.js:274:29
04.03.16 10:39:43 [+0100] at /usr/src/app/node_modules/async/lib/async.js:44:16
04.03.16 10:39:43 [+0100] at /usr/src/app/node_modules/async/lib/async.js:723:17
04.03.16 10:39:43 [+0100] at /usr/src/app/node_modules/async/lib/async.js:167:37
04.03.16 10:39:43 [+0100] at null._onTimeout (/usr/src/app/node_modules/async/lib/async.js:660:25)
04.03.16 10:39:43 [+0100] at Timer.listOnTimeout [as ontimeout] (timers.js:121:15)
```

When I check the os.networkInterfaces() I get only the eth0 :

```
{ lo:
04.03.16 10:39:43 [+0100] [ { address: '127.0.0.1', family: 'IPv4', internal: true },
04.03.16 10:39:43 [+0100] { address: '::1', family: 'IPv6', internal: true } ],
04.03.16 10:39:43 [+0100] eth0:
04.03.16 10:39:43 [+0100] [ { address: '192.168.0.22', family: 'IPv4', internal: false },
04.03.16 10:39:43 [+0100] { address: 'fe80::ba27:ebff:fe5b:a761',
04.03.16 10:39:43 [+0100] family: 'IPv6',
04.03.16 10:39:43 [+0100] internal: false } ] }
```

Any idea ? It's the first time I launch the app and the dongle has never been connected to the wifi. Plus, I downloanded and installed the resin.io basic image with ethernet in the RPi 2 without the wifi.

**Comment by pcarranzav** [comment]
Hi there @samouds.
It looks like the dongle is somehow not working properly. Can you check what driver is loaded using `lsmod`? Also `lsusb` might help confirm whether the dongle actually has the Ralink chipset.

Could you also post the full logs please? There might be something happening before the error to give us more insight.

**Comment by samouds** [comment]
@pcarranzav Thanks.

I see the results of lsmod and lsusb : 

```
root@raspberrypi2-e9b6b8:~# lsmod 
Module                  Size  Used by
bnep                   10740  2 
fuse                   83006  1 
xt_connmark             1667  2 
iptable_mangle          1334  1 
snd_bcm2835            20764  0 
snd_pcm                73405  1 snd_bcm2835
bluetooth             318087  7 bnep
snd_timer              17657  1 snd_pcm
snd                    50545  3 snd_bcm2835,snd_timer,snd_pcm
arc4                    1718  2 
rt2800usb              17560  0 
rt2800lib              71782  1 rt2800usb
rt2x00usb               8588  1 rt2800usb
rt2x00lib              36856  3 rt2x00usb,rt2800lib,rt2800usb
mac80211              539719  3 rt2x00lib,rt2x00usb,rt2800lib
cfg80211              424265  2 mac80211,rt2x00lib
crc_ccitt               1142  1 rt2800lib
rfkill                 17289  7 cfg80211,bluetooth
spi_bcm2835             7102  0 
i2c_bcm2708             4948  0 
bcm2835_gpiomem         2860  0 
uio_pdrv_genirq         2924  0 
uio                     7760  1 uio_pdrv_genirq
sch_fq_codel            7809  7 
```
```
root@raspberrypi2-e9b6b8:~# lsusb 
Bus 001 Device 004: ID 148f:5370 Ralink Technology, Corp. RT5370 Wireless Adapter
Bus 001 Device 003: ID 0424:ec00 Standard Microsystems Corp. SMSC9512/9514 Fast Ethernet Adapter
Bus 001 Device 002: ID 0424:9514 Standard Microsystems Corp. 
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

**Comment by pcarranzav** [comment]
Okay, that's weird, as everything seems to be okay with the driver.
Could you try changing the [retry interval](https://github.com/resin-io/resin-wifi-connect/blob/master/src/app.coffee#L31) to a higher value? Maybe it's just taking too long to set up the tether interface.
(btw, do you see the hotspot?)

**Comment by samouds** [comment]
@pcarranzav yes it's weird. I purged all data and restart from the beginning and all is working now.

I have a question, how can I reboot the device from the container in app.coffee or at least restart the app ?

**Comment by pcarranzav** [comment]
@samouds - weird, possibly the module just took too long to switch to AP mode... do let us know if it happens again.

Regarding your question, you can use the [Supervisor API](https://github.com/resin-io/resin-supervisor/blob/master/docs/API.md) for that.

**Comment by petrosagg** [comment]
@samouds the project a major update that makes it much more stable. Could you try the latest version?
