### ISSUE TITLE
Wifi does not come back up when the device is rebooted from within the application.

### ISSUE THREAD

**Issue by josephroberts** [resin-io/resin-wifi-connect#71]
Reported on the forums [here](https://forums.resin.io/t/rpi3-wifi-not-connecting-after-a-reboot-from-the-api/615)

Resin OS 1.24.1
Supervisor 2.8.3

**Comment by josephroberts** [comment]
I managed to reproduce this after several tries.

There is a 15 second timeout during which connman has to connect to the configured network, this is great when a network has not already been configured because it means the configuration loop is fairly quick in the event a user enters the wrong password, makes a typo etc. However, if the network has already been configured `resin-wifi-connect` will exit once the timeout has elapsed and in some cases the timeout is too short. Throwing this error:
```
Clear disabled
Using connman.service
Credentials found
Connecting
Error: Timed out
    at Timeout._onTimeout (/usr/src/app/src/connman.js:78:25)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
Not retrying
Exiting
```

**Comment by josephroberts** [comment]
I tried increasing the timeout which didn't help, so I changed `resin-wifi-connect` to wait until connman is up before attempting to connect. This seems to work
