### ISSUE TITLE
Error: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory

### ISSUE THREAD

**Issue by alberttwong** [resin-io/resin-wifi-connect#72]
started up... knows it's on wrong network.... I join resinap... put in the right network/passwd... joins right network... everything works fine.  restart app... knows it's on correct network and passes... everything works fine....  resin ssh into the container and I try to re-enter access point mode and then it goes into error. 

```
root@raspberrypi3-610a8e3:/app/pinballiot# node src/app.js --clear=true
/app/pinballiot/node_modules/dbus/lib/bus.js:18
		self.connection = dbus._dbus.getBus(0);
		                             ^

Error: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
    at new module.exports (/app/pinballiot/node_modules/dbus/lib/bus.js:18:32)
    at module.exports.DBus.getBus (/app/pinballiot/node_modules/dbus/lib/dbus.js:48:12)
    at Object.<anonymous> (/app/pinballiot/src/connman.js:13:14)
    at Object.<anonymous> (/app/pinballiot/src/connman.js:84:4)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/app/pinballiot/src/app.js:9:13)
    at Object.<anonymous> (/app/pinballiot/src/app.js:149:4)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
```

**Comment by josephroberts** [comment]
Hi,

You need to run `export DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket` before calling `node src/app.js --clear=true`

**Comment by lyon0417** [comment]
1. check your dbus-daemon running or not
2. find your path of system_bus_socket file, ex: /var/run/dbus/system_bus_socket 
maybe another path depends on your dbus building.
3. export DBUS_SYSTEM_BUS_ADDRESS="your system_bus_socket path"
