### ISSUE TITLE
Command failed: iw wlan0 scan ap-force

### ISSUE THREAD

**Issue by OllieLy** [resin-io/resin-wifi-connect#83]
Im on an Intel NUC running Resin OS 2.0.0+rev3 (prod), using the internal wifi.

Even on a clean push of this repo I get the below error on loop. 

```
  Clearing credentials
  Credentials not found
  { Error: Command failed: iw wlan0 scan ap-force

  at ChildProcess.exithandler (child_process.js:206:12)
  at emitTwo (events.js:106:13)
  at ChildProcess.emit (events.js:191:7)
  at maybeClose (internal/child_process.js:877:16)
  at Socket.<anonymous> (internal/child_process.js:334:11)
  at emitOne (events.js:96:13)
  at Socket.emit (events.js:188:7)
  at Pipe._handle.close [as _onclose] (net.js:498:12)
  cause:
  { Error: Command failed: iw wlan0 scan ap-force

  at ChildProcess.exithandler (child_process.js:206:12)
  at emitTwo (events.js:106:13)
  at ChildProcess.emit (events.js:191:7)
  at maybeClose (internal/child_process.js:877:16)
  at Socket.<anonymous> (internal/child_process.js:334:11)
  at emitOne (events.js:96:13)
  at Socket.emit (events.js:188:7)
  at Pipe._handle.close [as _onclose] (net.js:498:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'iw wlan0 scan ap-force' },
  isOperational: true,
  killed: false,
  code: 1,
  signal: null,
  cmd: 'iw wlan0 scan ap-force' }

```

**Comment by josephroberts** [comment]
I think this error is thrown because the internal wifi on the NUC is not called `wlan0`
Can you post the output of `iw dev` please

**Comment by OllieLy** [comment]
You were correct. Thanks!

Here is the output:

`        Interface wlp2s0
                ifindex 4
                wdev 0x1
                addr 82:84:b4:1c:1d:37
                type managed`

Changing the PORTAL_INTERFACE env to wlp2s0 fixed it.

**Comment by josephroberts** [comment]
Sweet, thanks for posting the solution!
